"""adding uuid for conversations

Revision ID: 07ae44748320
Revises: c09b511a8030
Create Date: 2022-03-11 10:09:54.412606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ae44748320'
down_revision = 'c09b511a8030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_uuid', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint("uq_conversations_conversation_uuid", ['conversation_uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint("uq_conversations_conversation_uuid", type_='unique')
        batch_op.drop_column('conversation_uuid')

    # ### end Alembic commands ###
