"""fixing content unique

Revision ID: 33bdd2530a4f
Revises: dfd729af6adb
Create Date: 2022-02-06 16:55:46.514762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bdd2530a4f'
down_revision = 'dfd729af6adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=280), nullable=True),
    sa.Column('recipient', sa.Integer(), nullable=True),
    sa.Column('time_sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('messages_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['messages_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
