"""removing message

Revision ID: 39b756c59fa8
Revises: 33bdd2530a4f
Create Date: 2022-02-08 11:48:34.888438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b756c59fa8'
down_revision = '33bdd2530a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_messages')
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=280), nullable=True),
    sa.Column('recipient', sa.INTEGER(), nullable=True),
    sa.Column('time_sent', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['recipient'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender', sa.INTEGER(), nullable=True),
    sa.Column('messages_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['messages_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
