"""empty message

Revision ID: 410fe575ca43
Revises: 6e7039f2cdb9
Create Date: 2022-02-03 13:09:16.420077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410fe575ca43'
down_revision = '6e7039f2cdb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_name')
    # ### end Alembic commands ###
