"""Adding api key

Revision ID: 621719b60182
Revises: 07ae44748320
Create Date: 2022-03-23 18:31:06.733569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621719b60182'
down_revision = '07ae44748320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
