"""Adding time sent for message

Revision ID: 8b7b9a8638e9
Revises: e25026ae2a8a
Create Date: 2022-02-06 11:35:21.012956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7b9a8638e9'
down_revision = 'e25026ae2a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('time_sent', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'time_sent')
    # ### end Alembic commands ###
