"""added unread message count

Revision ID: 97df8334f27c
Revises: f2e26504bd02
Create Date: 2022-03-09 09:44:03.767647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97df8334f27c'
down_revision = 'f2e26504bd02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unread_messages', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations_users', schema=None) as batch_op:
        batch_op.drop_column('unread_messages')

    # ### end Alembic commands ###
