"""empty message

Revision ID: f2e26504bd02
Revises: be7a5471d50a
Create Date: 2022-03-02 18:39:38.545973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e26504bd02'
down_revision = 'be7a5471d50a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('users', 'avatar_name', new_column_name='_avatar_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('users', '_avatar_hash', new_column_name='avatar_name')

    # ### end Alembic commands ###
